language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2
    - android-21
    - addon-google_apis-google-21
    - extra-android-m2repository
    - extra-android-support
    - tools
    - platform-tools