package com.namehillsoftware.projectblue.playback.engine.preparation;

import com.lasthopesoftware.bluewater.client.playback.engine.preparation.IPreparedPlaybackQueueConfiguration;
import com.namehillsoftware.projectblue.playback.file.preparation.PlayableFilePreparationSource;

public interface IPlayableFilePreparationSourceProvider extends IPreparedPlaybackQueueConfiguration {
	PlayableFilePreparationSource providePlayableFilePreparationSource();
}
